name: Run tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

env:
  PHP_EXTENSIONS: mbstring
  PHP_TOOLS: composer:v2, phpunit:9.5

jobs:
  run-tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: ${{ env.PHP_TOOLS }}
      
      - name: Determine composer cache directory
        id: determine-composer-cache-directory
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-
      
      # TODO test direct env php with github actios
      - name: Add config/env.test.php
        run: echo '${{ secrets.ENV_PHP }}' > $GITHUB_WORKSPACE/config/env.test.php

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --ignore-platform-reqs
      
      - name: Static analysis
        run: composer phpstan

      - name: PHPUnit tests
        run: composer test:unit

      - name: PHPUnit e2e tests
        if: ${{ vars.RUN_TESTS_E2E == 'true' }}
        run: composer test:e2e

      - name: Remove temp files
        run: rm -f $GITHUB_WORKSPACE/auth.json, $GITHUB_WORKSPACE/config/env.test.php
